export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'

export const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS'
export const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS'

export const OPEN = 'OPEN'
export const CLOSE = 'CLOSE'









