export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'

export const OPEN = 'OPEN'
export const CLOSE = 'CLOSE'
export const ADD_USER = 'ADD_USER'
export const GET_USER_FULL_INFO = 'GET_USER_FULL_INFO'
export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_FULL_INFO = 'EDIT_USER_FULL_INFO'
export const DELETE_USER = 'DELETE_USER'
export const ALL_CONTACTS = 'ALL_CONTACTS'







