export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'

export const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS'
export const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS'

export const OPEN = 'OPEN'
export const CLOSE = 'CLOSE'

export const GET_USER_FULL_INFO = 'GET_USER_FULL_INFO'
export const EDIT_USER = 'EDIT_USER'
export const EDIT_USER_FULL_INFO = 'EDIT_USER_FULL_INFO'








