// CONTACTS

export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'

export const FETCH_DELETE_SUCCESS = 'FETCH_DELETE_SUCCESS'
export const FETCH_ADD_SUCCESS = 'FETCH_ADD_SUCCESS'

// CATEGORIES

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

export const FETCH_ADD_CATEGORY_SUCCESS = 'FETCH_ADD_CATEGORY_SUCCESS'
export const FETCH_DELETE_CATEGORY_SUCCESS = 'FETCH_DELETE_CATEGORY_SUCCESS'

// SIDEBAR

export const OPEN = 'OPEN'
export const CLOSE = 'CLOSE'











